version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2
    AWS_ACCOUNT_ID: 009160047497
    FRONTEND_BUCKET_NAME: job-a-dream-frontend
    DISTRIBUTION_ID: E2NS2PMHDJZ9LA

phases:
  pre_build:
    commands:
      - echo Installing pnpm using npm...
      - npm install -g pnpm  # pnpm을 npm을 통해 전역 설치
      - export PNPM_HOME=$(npm root -g)/pnpm
      - export PATH=$PNPM_HOME:$PATH
      - echo Installing frontend dependencies with pnpm...
      - cd job-a-dream-frontend  # 프론트엔드 경로로 이동
      - pnpm install  # pnpm을 사용해 의존성 설치
  build:
    commands:
      - echo Building frontend with pnpm and Vite...
      - pnpm run build  # Vite를 사용해 프로젝트 빌드
      - ls -al ./dist/  # dist 디렉토리 확인 (디버깅용)
  post_build:
    commands:
      - echo Deploying frontend to S3...
      - aws s3 sync ./dist/ s3://$FRONTEND_BUCKET_NAME --delete  # dist 디렉토리를 S3로 업로드
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"

artifacts:
  files:
    - dist/**/*  # 빌드된 정적 파일을 아티팩트로 설정